# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: Build_LibGit2
  timeoutInMinutes: 0
  pool:
    vmImage: macOS-10.15

  steps:

  - script: ./build-tools.sh
    displayName: 'Build autoconf, automake and libtool for local use'
    enabled: false

  - publish: $(System.DefaultWorkingDirectory)/tools.tar.xz
    artifact: BuildTools
    displayName: 'Publish auto build tools'
    enabled: false

  - script: ./build-libgit2-framework.sh
    displayName: 'Build LibGit2 Framework from Source'
    continueOnError: false
    enabled: true

  - publish: $(System.DefaultWorkingDirectory)/Clibgit2.xcframework.tar.xz
    artifact: Clibgit2
    displayName: 'Publish Clibgit2 XCFramework'
    enabled: false

  - publish: $(System.DefaultWorkingDirectory)/PCRE.xcframework.tar.xz
    artifact: PCRE
    displayName: 'Publish LibPCRE XCFramework'
    enabled: false

  - publish: $(System.DefaultWorkingDirectory)/Clibgit2.xcframework
    artifact: Clibgit2Folder
    displayName: 'Publish Clibgit2 Folder for Inspection'
    enabled: false

  - publish: $(System.DefaultWorkingDirectory)/openssl-OpenSSL_1_1_1k
    artifact: OpenSSL
    displayName: 'Publish OpenSSL Folder for Inspection'
    enabled: false

  - publish: $(System.DefaultWorkingDirectory)
    artifact: AllFiles
    displayName: 'Publish all files for inspection'
    enabled: true
