name: Build
on: [push]
jobs:
  build-libgit2-xcframework:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./build-tools.sh
      - run: ./build-libgit2-framework.sh

